import Container from "@mui/material/Container"
import Head from "next/head"

export default function AppLayout({ children }) {
    return (
        <>
            <Head>
                <title>WifiRepo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container
                component="main"
                fixed
                sx={{
                    backgroundColor: "white",
                    borderRadius: "10px",
                    boxShadow: 3,
                    height: {
                        xs: "100%",
                        sm: "90vh",
                    },
                    width: {
                        xs: "100%",
                        sm: "500px",
                    },
                    overflow: "hidden",
                }}
            >
                {children}
            </Container>
        </>
    )
}
