import { useEffect } from "react"
import Alert from "@mui/material/Alert"
import Container from "@mui/material/Container"
import Head from "next/head"

import useStore from "src/store"

export default function AppLayout({ children }) {
    const message = useStore((state) => state.message)
    const severity = useStore((state) => state.severity)
    const clearAlert = useStore((state) => state.clearAlert)

    useEffect(() => {
        return () => {
            clearAlert()
        }
    }, [])

    return (
        <>
            <Head>
                <title>WifiRepo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                disableGutters
                component="main"
                fixed
                sx={{
                    backgroundColor: "white",
                    borderRadius: "10px",
                    boxShadow: 3,
                    height: {
                        xs: "100%",
                        sm: "90vh",
                    },
                    width: {
                        xs: "100%",
                        sm: "500px",
                    },
                    overflow: "hidden",
                }}
            >
                {children}
            </Container>

            {message && (
                <Alert
                    onClose={() => clearAlert()}
                    severity={severity || "info"}
                    sx={{
                        position: "fixed",
                        width: {
                            xs: "80%",
                            sm: "50%",
                        },
                        bottom: 20,
                        left: {
                            sx: "20%",
                            sm: "50%",
                        },
                        marginLeft: {
                            xs: 0,
                            sm: "-25%",
                        },
                    }}
                >
                    {message}
                </Alert>
            )}
        </>
    )
}
